language: go
go:
- '1.15'
services:
- docker
script:
- make
after_success:
- echo "$QUAY_BOT_PASSWORD" | docker login --username "$QUAY_BOT_USERNAME" --password-stdin
  quay.io
- make docker-build
- make docker-push
notifications:
  slack:
    secure: NXmK/BpZzYm3TyHyTg5Wnjm+155lUA62v/nzxO9VnF8xJxowO11GshigPNFgzVc2vTM5mhN04HmV8A1p3ySxDwQ2KHuk5DJLrEWkdvtE/+BFQ8m8PrvTf8jKILLT1B2G/wmXO+65zTcicWyhtuo0JTH3evB/XAV1vc3wwzeUYT4qpqS6T3V0Cku5q8bei7vVtZAountNCi6NTnuyEyjO/J9FaChjzM9YP8cWjM7H44c5Gw4WOVojFo+SdrKZUf+KWLdy849xOm77qhZpMwaLvvfUJjl4poaHCEiup8Cqhb409B0zJRqpZ/diGLv93aFVXqzyuvCeAqVcKEu+7sIXLc4Svx80QkGCIo/aVNg8dDKDIso/UiDlIE2/vGiQQATnovmz/htEAsv19+o7oTdzzk/r8fEdb0QgkVnLgH4bXDdprMYKAF/jxhnwoYhM0bkseuaeIgUwGYc5zg+ylBltV5bIw4mf4JENPDVS/GFZlAbQgVQIPZY/VUBHBXi9nQm07qKaDIS37lQdmP2Rl70pvygSRlX2WB1ia7PFJBPsMEszZUFzaYGDbYlFB8cA8MmmBNoRZC5KeyvjpnWBJwI/FhjMZA2cg8o9jRRuIxr9vtH8RIfUQkzBMsvPDcidkuL4GGulpxWXPAV5LO+pNnEuOLWaqCAQBWEBcbGP9YslbOs=
